Question 1: -
Write a program that takes a string as input, and counts the frequency of each word in the string, there might
be repeated characters in the string. Your task is to find the highest frequency and returns the length of the
highest-frequency word.

Note - You have to write at least 2 additional test cases in which your program will run successfully and provide
an explanation for the same.
Example input - string = “write write write all the number from from from 1 to 100”
Example output - 5
Explanation - From the given string we can note that the most frequent words are “write” and “from” and
the maximum value of both the values is “write” and its corresponding length is 5

In [1]:
def highest_frequency_length(string):
    # Split the string into words
    words = string.split()

    # Create a dictionary to store the frequency of each word
    word_freq = {}
    for word in words:
        if word in word_freq:
            word_freq[word] += 1
        else:
            word_freq[word] = 1
            
    max_frequency = max(word_freq.values())
    max_length = 0
    for word, frequency in word_freq.items():
        if frequency == max_frequency and len(word) > max_length:
            max_length = len(word)

    return max_length


string1 = "apple apple banana orange banana orange orange"
print(highest_frequency_length(string1)) 

string2 = "cat dog cow"
print(highest_frequency_length(string2))

6
3

Question 2: -
Consider a string to be valid if all characters of the string appear the same number of times. It is also valid if
he can remove just one character at the index in the string, and the remaining characters will occur the same
number of times. Given a string, determine if it is valid. If so, return YES , otherwise return NO .

Note - You have to write at least 2 additional test cases in which your program will run successfully and provide
an explanation for the same.
Example input 1 - s = “abc”. This is a valid string because frequencies are { “a”: 1, “b”: 1, “c”: 1 }
Example output 1- YES
Example input 2 - s “abcc”. This string is not valid as we can remove only 1 occurrence of “c”. That leaves
character frequencies of { “a”: 1, “b”: 1 , “c”: 2 }
Example output 2 - NO

In [2]:
def is_valid_string(s):
    char_freq = {} 
    
   
    for char in s:
        if char in char_freq:
            char_freq[char] += 1
        else:
            char_freq[char] = 1

   
    if len(set(char_freq.values())) == 1:
        return "YES"
    
   
    for freq in char_freq.values():
        if list(char_freq.values()).count(freq) == len(char_freq) - 1:
            return "YES"

    return "NO"

print(is_valid_string("abc"))  
print(is_valid_string("abcc"))  

print(is_valid_string("aaabbbccdd"))

YES
YES
NO

Question 3: -
Write a program, which would download the data from the provided link, and then read the data and convert
that into properly structured data and return it in Excel format.
Note - Write comments wherever necessary explaining the code written.

Link - https://raw.githubusercontent.com/Biuni/PokemonGO-Pokedex/master/pokedex.json
Data Attributes - id: Identification Number - int num: Number of the
● Pokémon in the official Pokédex - int name: Pokémon name -
● string img: URL to an image of this Pokémon - string type:
● Pokémon type -string height: Pokémon height - float
● weight: Pokémon weight - float candy: type of candy used to evolve Pokémon or
given
● when transferred - string candy_count: the amount of candies required to evolve
- int
● egg: Number of kilometers to travel to hatch the egg - float spawn_chance:
● Percentage of spawn chance (NEW) - float avg_spawns: Number of this
pokemon on 10.000 spawns (NEW) - int
● spawn_time: Spawns most active at the time on this field. Spawn times are the same for all
time zones and are expressed in local time. (NEW) - “minutes: seconds” multipliers:
Multiplier of Combat Power (CP) for calculating the CP after evolution See below - list of int
weakness: Types of
● Pokémon this Pokémon is weak to - list of strings next_evolution: Number and Name of
successive evolutions of Pokémon - list of dict prev_evolution: Number and Name of previous
evolutions of Pokémon - - list of dict

In [4]:
import pandas as pd
import json
import requests

# Fetch the JSON data from the URL
url = "https://raw.githubusercontent.com/Biuni/PokemonGO-Pokedex/master/pokedex.json"
response = requests.get(url)
data = response.json()

# Extract the relevant information from the JSON data
pokemon_data = data["pokemon"]

# Convert the data into a pandas DataFrame
df = pd.DataFrame(pokemon_data)
excel_data = df.to_excel('pokemon_data.xlsx', index=False)

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution
0,1,001,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"[Grass, Poison]",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,0.6900,69.00,20:00,[1.58],"[Fire, Ice, Flying, Psychic]","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN
1,2,002,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"[Grass, Poison]",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,0.0420,4.20,07:00,"[1.2, 1.6]","[Fire, Ice, Flying, Psychic]","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]"
2,3,003,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"[Grass, Poison]",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,0.0170,1.70,11:30,None,"[Fire, Ice, Flying, Psychic]",NaN,"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ..."
3,4,004,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,[Fire],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,0.2530,25.30,08:45,[1.65],"[Water, Ground, Rock]","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",NaN
4,5,005,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,[Fire],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.0120,1.20,19:00,[1.79],"[Water, Ground, Rock]","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,147,147,Dratini,http://www.serebii.net/pokemongo/pokemon/147.png,[Dragon],1.80 m,3.3 kg,Dratini Candy,25.0,10 km,0.3000,30.00,06:41,"[1.83, 1.84]","[Ice, Dragon, Fairy]","[{'num': '148', 'name': 'Dragonair'}, {'num': ...",NaN
147,148,148,Dragonair,http://www.serebii.net/pokemongo/pokemon/148.png,[Dragon],3.99 m,16.5 kg,Dratini Candy,100.0,Not in Eggs,0.0200,2.00,11:57,[2.05],"[Ice, Dragon, Fairy]","[{'num': '149', 'name': 'Dragonite'}]","[{'num': '147', 'name': 'Dratini'}]"
148,149,149,Dragonite,http://www.serebii.net/pokemongo/pokemon/149.png,"[Dragon, Flying]",2.21 m,210.0 kg,Dratini Candy,NaN,Not in Eggs,0.0011,0.11,23:38,None,"[Ice, Rock, Dragon, Fairy]",NaN,"[{'num': '147', 'name': 'Dratini'}, {'num': '1..."
149,150,150,Mewtwo,http://www.serebii.net/pokemongo/pokemon/150.png,[Psychic],2.01 m,122.0 kg,None,NaN,Not in Eggs,0.0000,0.00,N/A,None,"[Bug, Ghost, Dark]",NaN,NaN
150,151,151,Mew,http://www.serebii.net/pokemongo/pokemon/151.png,[Psychic],0.41 m,4.0 kg,None,NaN,Not in Eggs,0.0000,0.00,N/A,None,"[Bug, Ghost, Dark]",NaN,NaN

Question 4 -
Write a program to download the data from the link given below and then read the data and convert the into
the proper structure and return it as a CSV file.
Link - https://data.nasa.gov/resource/y77d-th95.json
Note - Write code comments wherever needed for code understanding.

Sample Data -




Excepted Output Data Attributes
● Name of Earth Meteorite - string id - ID of Earth
● Meteorite - int nametype - string recclass - string
● mass - Mass of Earth Meteorite - float year - Year at which Earth
● Meteorite was hit - datetime format reclat - float recclong - float
● point coordinates - list of int

In [9]:
import pandas as pd
import json
import requests

# Fetch the data from the URL
url = "https://data.nasa.gov/resource/y77d-th95.json"
response = requests.get(url)
data = response.json()

# Convert the data into a structured format
meteorite_data = []
for meteorite in data:
    meteorite_entry = {
        'name': meteorite.get('name', ''),
        'id': meteorite.get('id', ''),
        'nametype': meteorite.get('nametype', ''),
        'recclass': meteorite.get('recclass', ''),
        'mass': meteorite.get('mass (g)', ''),
        'year': meteorite.get('year', ''),
        'reclat': meteorite.get('reclat', ''),
        'reclong': meteorite.get('reclong', ''),
        'coordinates': [meteorite.get('reclat', ''), meteorite.get('reclong', '')]
    }
    meteorite_data.append(meteorite_entry)
print( meteorite_entry)
    

# Convert the structured data into a CSV file
df = pd.DataFrame(meteorite_data)
csv_data = df.to_csv('meteorite_data.csv', index=False)
df

{'name': 'Tomakovka', 'id': '24019', 'nametype': 'Valid', 'recclass': 'LL6', 'mass': '', 'year': '1905-01-01T00:00:00.000', 'reclat': '47.850000', 'reclong': '34.766670', 'coordinates': ['47.850000', '34.766670']}

,name,id,nametype,recclass,mass,year,reclat,reclong,coordinates
0,Aachen,1,Valid,L5,,1880-01-01T00:00:00.000,50.775000,6.083330,"[50.775000, 6.083330]"
1,Aarhus,2,Valid,H6,,1951-01-01T00:00:00.000,56.183330,10.233330,"[56.183330, 10.233330]"
2,Abee,6,Valid,EH4,,1952-01-01T00:00:00.000,54.216670,-113.000000,"[54.216670, -113.000000]"
3,Acapulco,10,Valid,Acapulcoite,,1976-01-01T00:00:00.000,16.883330,-99.900000,"[16.883330, -99.900000]"
4,Achiras,370,Valid,L6,,1902-01-01T00:00:00.000,-33.166670,-64.950000,"[-33.166670, -64.950000]"
...,...,...,...,...,...,...,...,...,...
995,Tirupati,24009,Valid,H6,,1934-01-01T00:00:00.000,13.633330,79.416670,"[13.633330, 79.416670]"
996,Tissint,54823,Valid,Martian (shergottite),,2011-01-01T00:00:00.000,29.481950,-7.611230,"[29.481950, -7.611230]"
997,Tjabe,24011,Valid,H6,,1869-01-01T00:00:00.000,-7.083330,111.533330,"[-7.083330, 111.533330]"
998,Tjerebon,24012,Valid,L5,,1922-01-01T00:00:00.000,-6.666670,106.583330,"[-6.666670, 106.583330]"
999,Tomakovka,24019,Valid,LL6,,1905-01-01T00:00:00.000,47.850000,34.766670,"[47.850000, 34.766670]"

In [ ]:
Question 5 -
Write a program to download the data from the given API link and then extract the following data with
proper formatting

Link - http://api.tvmaze.com/singlesearch/shows?q=westworld&embed=episodes
Note - Write proper code comments wherever needed for the code understanding

Sample Data -

Excepted Output Data Attributes -
● id - int url - string
● name - string season
● - int number - int
● type - string airdate -
● date format airtime -
● 12-hour time format
● runtime - float
● average rating - float
● summary - string
● without html tags
● medium image link - string
● Original image link - string

In [1]:
import requests
import pandas as pd

# API URL
api_url = "http://api.tvmaze.com/singlesearch/shows?q=westworld&embed=episodes"

# Send GET request to the API URL and retrieve the response
response = requests.get(api_url)

# Extract relevant data from the response
data = response.json()

# Extract episode data from the embedded episodes
episodes = data["_embedded"]["episodes"]

# Create a DataFrame to store the extracted data
df = pd.DataFrame(episodes)

# Specify the columns to keep
columns_to_keep = ["season", "number", "name", "airdate", "airtime", "runtime", "summary"]

# Filter the DataFrame to keep only the specified columns
df = df[columns_to_keep]

# Convert the airdate column to datetime format
df["airdate"] = pd.to_datetime(df["airdate"])

# Save the DataFrame as a CSV file
df.to_csv("westworld_episodes.csv", index=False)

# Print a message to confirm successful conversion
print("Data has been saved as westworld_episodes.csv")

Data has been saved as westworld_episodes.csv

In [ ]:
Question 6 -

Using the data from Question 3, write code to analyze the data and answer the following questions Note 1.
Draw plots to demonstrate the analysis for the following questions for better visualizations.
2. Write code comments wherever required for code understanding

Insights to be drawn -
● Get all Pokemons whose spawn rate is less than 5%
● Get all Pokemons that have less than 4 weaknesses
● Get all Pokemons that have no multipliers at all
● Get all Pokemons that do not have more than 2 evolutions
● Get all Pokemons whose spawn time is less than 300 seconds.
Note - spawn time format is "05:32”, so assume “minute: second” format and perform the analysis.
● Get all Pokemon who have more than two types of capabilities

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

#Read the Pokemon data from the xlxs file

df = pd.read_excel('pokemon_data.xlsx')
df

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution
0,1,1,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"['Grass', 'Poison']",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,0.6900,69.00,20:00,[1.58],"['Fire', 'Ice', 'Flying', 'Psychic']","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN
1,2,2,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"['Grass', 'Poison']",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,0.0420,4.20,07:00,"[1.2, 1.6]","['Fire', 'Ice', 'Flying', 'Psychic']","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]"
2,3,3,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"['Grass', 'Poison']",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,0.0170,1.70,11:30,NaN,"['Fire', 'Ice', 'Flying', 'Psychic']",NaN,"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ..."
3,4,4,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,['Fire'],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,0.2530,25.30,08:45,[1.65],"['Water', 'Ground', 'Rock']","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",NaN
4,5,5,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,['Fire'],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.0120,1.20,19:00,[1.79],"['Water', 'Ground', 'Rock']","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,147,147,Dratini,http://www.serebii.net/pokemongo/pokemon/147.png,['Dragon'],1.80 m,3.3 kg,Dratini Candy,25.0,10 km,0.3000,30.00,06:41,"[1.83, 1.84]","['Ice', 'Dragon', 'Fairy']","[{'num': '148', 'name': 'Dragonair'}, {'num': ...",NaN
147,148,148,Dragonair,http://www.serebii.net/pokemongo/pokemon/148.png,['Dragon'],3.99 m,16.5 kg,Dratini Candy,100.0,Not in Eggs,0.0200,2.00,11:57,[2.05],"['Ice', 'Dragon', 'Fairy']","[{'num': '149', 'name': 'Dragonite'}]","[{'num': '147', 'name': 'Dratini'}]"
148,149,149,Dragonite,http://www.serebii.net/pokemongo/pokemon/149.png,"['Dragon', 'Flying']",2.21 m,210.0 kg,Dratini Candy,NaN,Not in Eggs,0.0011,0.11,23:38,NaN,"['Ice', 'Rock', 'Dragon', 'Fairy']",NaN,"[{'num': '147', 'name': 'Dratini'}, {'num': '1..."
149,150,150,Mewtwo,http://www.serebii.net/pokemongo/pokemon/150.png,['Psychic'],2.01 m,122.0 kg,None,NaN,Not in Eggs,0.0000,0.00,NaN,NaN,"['Bug', 'Ghost', 'Dark']",NaN,NaN
150,151,151,Mew,http://www.serebii.net/pokemongo/pokemon/151.png,['Psychic'],0.41 m,4.0 kg,None,NaN,Not in Eggs,0.0000,0.00,NaN,NaN,"['Bug', 'Ghost', 'Dark']",NaN,NaN

In [ ]:
df[df['spawn_chance'] < 5]
df
spawn_rate_less_than_5 = df[df['spawn_chance'] < 5]

#Bar plot for spawn rate analysis
plt.figure(figsize=(8, 6))
plt.bar(spawn_rate_less_than_5['name'], spawn_rate_less_than_5['spawn_chance'])
plt.xlabel('Pokemon')
plt.ylabel('Spawn Rate')
plt.title('Pokemons with Spawn Rate less than 5%')
plt.xticks(rotation=90)
plt.show()

In [ ]:
df[df['weaknesses'].str.count(',') < 3]
df

less_than_4_weaknesses = df[df['weaknesses'].str.count(',') < 3]

plt.figure(figsize=(8, 6))
plt.pie([len(df) - len(less_than_4_weaknesses), len(less_than_4_weaknesses)], labels=['More than 4 Weaknesses', 'Less than 4 Weaknesses'], autopct='%1.1f%%')
plt.title('Pokemons with Less than 4 Weaknesses')
plt.show()

In [4]:
df[df['multipliers'].isnull()]

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution,spawn_time_seconds
2,3,3,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"['Grass', 'Poison']",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,0.0170,1.70,11:30,NaN,"['Fire', 'Ice', 'Flying', 'Psychic']",NaN,"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ...",690.0
5,6,6,Charizard,http://www.serebii.net/pokemongo/pokemon/006.png,"['Fire', 'Flying']",1.70 m,90.5 kg,Charmander Candy,NaN,Not in Eggs,0.0031,0.31,13:34,NaN,"['Water', 'Electric', 'Rock']",NaN,"[{'num': '004', 'name': 'Charmander'}, {'num':...",814.0
8,9,9,Blastoise,http://www.serebii.net/pokemongo/pokemon/009.png,['Water'],1.60 m,85.5 kg,Squirtle Candy,NaN,Not in Eggs,0.0067,0.67,00:06,NaN,"['Electric', 'Grass']",NaN,"[{'num': '007', 'name': 'Squirtle'}, {'num': '...",6.0
11,12,12,Butterfree,http://www.serebii.net/pokemongo/pokemon/012.png,"['Bug', 'Flying']",1.09 m,32.0 kg,Caterpie Candy,NaN,Not in Eggs,0.0220,2.20,05:23,NaN,"['Fire', 'Electric', 'Ice', 'Flying', 'Rock']",NaN,"[{'num': '010', 'name': 'Caterpie'}, {'num': '...",323.0
14,15,15,Beedrill,http://www.serebii.net/pokemongo/pokemon/015.png,"['Bug', 'Poison']",0.99 m,29.5 kg,Weedle Candy,NaN,Not in Eggs,0.0510,5.10,04:50,NaN,"['Fire', 'Flying', 'Psychic', 'Rock']",NaN,"[{'num': '013', 'name': 'Weedle'}, {'num': '01...",290.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,145,145,Zapdos,http://www.serebii.net/pokemongo/pokemon/145.png,"['Electric', 'Flying']",1.60 m,52.6 kg,None,NaN,Not in Eggs,0.0000,0.00,NaN,NaN,"['Ice', 'Rock']",NaN,NaN,NaN
145,146,146,Moltres,http://www.serebii.net/pokemongo/pokemon/146.png,"['Fire', 'Flying']",2.01 m,60.0 kg,None,NaN,Not in Eggs,0.0000,0.00,NaN,NaN,"['Water', 'Electric', 'Rock']",NaN,NaN,NaN
148,149,149,Dragonite,http://www.serebii.net/pokemongo/pokemon/149.png,"['Dragon', 'Flying']",2.21 m,210.0 kg,Dratini Candy,NaN,Not in Eggs,0.0011,0.11,23:38,NaN,"['Ice', 'Rock', 'Dragon', 'Fairy']",NaN,"[{'num': '147', 'name': 'Dratini'}, {'num': '1...",1418.0
149,150,150,Mewtwo,http://www.serebii.net/pokemongo/pokemon/150.png,['Psychic'],2.01 m,122.0 kg,None,NaN,Not in Eggs,0.0000,0.00,NaN,NaN,"['Bug', 'Ghost', 'Dark']",NaN,NaN,NaN
150,151,151,Mew,http://www.serebii.net/pokemongo/pokemon/151.png,['Psychic'],0.41 m,4.0 kg,None,NaN,Not in Eggs,0.0000,0.00,NaN,NaN,"['Bug', 'Ghost', 'Dark']",NaN,NaN,NaN

In [5]:
df[df['next_evolution'].str.count(',') + 1)]

less_than_2_evolutions=df[df['next_evolution'].str.count(',') + 1)]

plt.figure(figsize=(8, 6))
plt.bar(less_than_2_evolutions['name'], less_than_2_evolutions['next_evolution'].str.count(',') + 1)
plt.xlabel('Pokemon')
plt.ylabel('Number of Evolutions')
plt.title('Pokemons with Less than 2 Evolutions')
plt.xticks(rotation=90)
plt.show()

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution,spawn_time_seconds
1,2,2,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"['Grass', 'Poison']",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,0.042,4.200,07:00,"[1.2, 1.6]","['Fire', 'Ice', 'Flying', 'Psychic']","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]",420.0
4,5,5,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,['Fire'],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.012,1.200,19:00,[1.79],"['Water', 'Ground', 'Rock']","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]",1140.0
7,8,8,Wartortle,http://www.serebii.net/pokemongo/pokemon/008.png,['Water'],0.99 m,22.5 kg,Squirtle Candy,100.0,Not in Eggs,0.034,3.400,07:02,[1.4],"['Electric', 'Grass']","[{'num': '009', 'name': 'Blastoise'}]","[{'num': '007', 'name': 'Squirtle'}]",422.0
10,11,11,Metapod,http://www.serebii.net/pokemongo/pokemon/011.png,['Bug'],0.71 m,9.9 kg,Caterpie Candy,50.0,Not in Eggs,0.187,18.700,02:11,"[3.55, 3.79]","['Fire', 'Flying', 'Rock']","[{'num': '012', 'name': 'Butterfree'}]","[{'num': '010', 'name': 'Caterpie'}]",131.0
13,14,14,Kakuna,http://www.serebii.net/pokemongo/pokemon/014.png,"['Bug', 'Poison']",0.61 m,10.0 kg,Weedle Candy,50.0,Not in Eggs,0.440,44.000,02:30,"[3.01, 3.41]","['Fire', 'Flying', 'Psychic', 'Rock']","[{'num': '015', 'name': 'Beedrill'}]","[{'num': '013', 'name': 'Weedle'}]",150.0
16,17,17,Pidgeotto,http://www.serebii.net/pokemongo/pokemon/017.png,"['Normal', 'Flying']",1.09 m,30.0 kg,Pidgey Candy,50.0,Not in Eggs,1.020,102.000,01:30,[1.79],"['Electric', 'Rock']","[{'num': '018', 'name': 'Pidgeot'}]","[{'num': '016', 'name': 'Pidgey'}]",90.0
18,19,19,Rattata,http://www.serebii.net/pokemongo/pokemon/019.png,['Normal'],0.30 m,3.5 kg,Rattata Candy,25.0,2 km,13.050,1.305,01:55,"[2.55, 2.73]",['Fighting'],"[{'num': '020', 'name': 'Raticate'}]",NaN,115.0
20,21,21,Spearow,http://www.serebii.net/pokemongo/pokemon/021.png,"['Normal', 'Flying']",0.30 m,2.0 kg,Spearow Candy,50.0,2 km,4.730,473.000,12:25,"[2.66, 2.68]","['Electric', 'Rock']","[{'num': '022', 'name': 'Fearow'}]",NaN,745.0
22,23,23,Ekans,http://www.serebii.net/pokemongo/pokemon/023.png,['Poison'],2.01 m,6.9 kg,Ekans Candy,50.0,5 km,2.270,227.000,12:20,"[2.21, 2.27]","['Ground', 'Psychic']","[{'num': '024', 'name': 'Arbok'}]",NaN,740.0
24,25,25,Pikachu,http://www.serebii.net/pokemongo/pokemon/025.png,['Electric'],0.41 m,6.0 kg,Pikachu Candy,50.0,2 km,0.210,21.000,04:00,[2.34],['Ground'],"[{'num': '026', 'name': 'Raichu'}]",NaN,240.0
26,27,27,Sandshrew,http://www.serebii.net/pokemongo/pokemon/027.png,['Ground'],0.61 m,12.0 kg,Sandshrew Candy,50.0,5 km,1.110,111.000,01:58,[2.45],"['Water', 'Grass', 'Ice']","[{'num': '028', 'name': 'Sandslash'}]",NaN,118.0
29,30,30,Nidorina,http://www.serebii.net/pokemongo/pokemon/030.png,['Poison'],0.79 m,20.0 kg,Nidoran ♀ (Female) Candy,100.0,Not in Eggs,0.088,8.800,07:22,"[1.83, 2.48]","['Ground', 'Psychic']","[{'num': '031', 'name': 'Nidoqueen'}]","[{'num': '029', 'name': 'Nidoran(Female)'}]",442.0
32,33,33,Nidorino,http://www.serebii.net/pokemongo/pokemon/033.png,['Poison'],0.89 m,19.5 kg,Nidoran ♂ (Male) Candy,100.0,Not in Eggs,0.083,8.300,09:02,[1.83],"['Ground', 'Psychic']","[{'num': '034', 'name': 'Nidoking'}]","[{'num': '032', 'name': 'Nidoran(Male)'}]",542.0
34,35,35,Clefairy,http://www.serebii.net/pokemongo/pokemon/035.png,['Normal'],0.61 m,7.5 kg,Clefairy Candy,50.0,2 km,0.920,92.000,03:30,"[2.03, 2.14]",['Fighting'],"[{'num': '036', 'name': 'Clefable'}]",NaN,210.0
36,37,37,Vulpix,http://www.serebii.net/pokemongo/pokemon/037.png,['Fire'],0.61 m,9.9 kg,Vulpix Candy,50.0,5 km,0.220,22.000,13:43,"[2.74, 2.81]","['Water', 'Ground', 'Rock']","[{'num': '038', 'name': 'Ninetales'}]",NaN,823.0
38,39,39,Jigglypuff,http://www.serebii.net/pokemongo/pokemon/039.png,['Normal'],0.51 m,5.5 kg,Jigglypuff Candy,50.0,2 km,0.390,39.000,08:46,[1.85],['Fighting'],"[{'num': '040', 'name': 'Wigglytuff'}]",NaN,526.0
40,41,41,Zubat,http://www.serebii.net/pokemongo/pokemon/041.png,"['Poison', 'Flying']",0.79 m,7.5 kg,Zubat Candy,50.0,2 km,6.520,652.000,12:28,"[2.6, 3.67]","['Electric', 'Ice', 'Psychic', 'Rock']","[{'num': '042', 'name': 'Golbat'}]",NaN,748.0
43,44,44,Gloom,http://www.serebii.net/pokemongo/pokemon/044.png,"['Grass', 'Poison']",0.79 m,8.6 kg,Oddish Candy,100.0,Not in Eggs,0.064,6.400,11:33,[1.49],"['Fire', 'Ice', 'Flying', 'Psychic']","[{'num': '045', 'name': 'Vileplume'}]","[{'num': '043', 'name': 'Oddish'}]",693.0
45,46,46,Paras,http://www.serebii.net/pokemongo/pokemon/046.png,"['Bug', 'Grass']",0.30 m,5.4 kg,Paras Candy,50.0,5 km,2.360,236.000,01:42,[2.02],"['Fire', 'Ice', 'Poison', 'Flying', 'Bug', 'Ro...","[{'num': '047', 'name': 'Parasect'}]",NaN,102.0
47,48,48,Venonat,http://www.serebii.net/pokemongo/pokemon/048.png,"['Bug', 'Poison']",0.99 m,30.0 kg,Venonat Candy,50.0,5 km,2.280,228.000,02:31,"[1.86, 1.9]","['Fire', 'Flying', 'Psychic', 'Rock']","[{'num': '049', 'name': 'Venomoth'}]",NaN,151.0
49,50,50,Diglett,http://www.serebii.net/pokemongo/pokemon/050.png,['Ground'],0.20 m,0.8 kg,Diglett Candy,50.0,5 km,0.400,40.000,02:22,[2.69],"['Water', 'Grass', 'Ice']","[{'num': '051', 'name': 'Dugtrio'}]",NaN,142.0
51,52,52,Meowth,http://www.serebii.net/pokemongo/pokemon/052.png,['Normal'],0.41 m,4.2 kg,Meowth Candy,50.0,5 km,0.860,86.000,02:54,[1.98],['Fighting'],"[{'num': '053', 'name': 'Persian'}]",NaN,174.0
53,54,54,Psyduck,http://www.serebii.net/pokemongo/pokemon/054.png,['Water'],0.79 m,19.6 kg,Psyduck Candy,50.0,5 km,2.540,254.000,03:41,[2.27],"['Electric', 'Grass']","[{'num': '055', 'name': 'Golduck'}]",NaN,221.0
55,56,56,Mankey,http://www.serebii.net/pokemongo/pokemon/056.png,['Fighting'],0.51 m,28.0 kg,Mankey Candy,50.0,5 km,0.920,92.000,12:52,"[2.17, 2.28]","['Flying', 'Psychic', 'Fairy']","[{'num': '057', 'name': 'Primeape'}]",NaN,772.0
57,58,58,Growlithe,http://www.serebii.net/pokemongo/pokemon/058.png,['Fire'],0.71 m,19.0 kg,Growlithe Candy,50.0,5 km,0.920,92.000,03:57,"[2.31, 2.36]","['Water', 'Ground', 'Rock']","[{'num': '059', 'name': 'Arcanine'}]",NaN,237.0
60,61,61,Poliwhirl,http://www.serebii.net/pokemongo/pokemon/061.png,['Water'],0.99 m,20.0 kg,Poliwag Candy,100.0,Not in Eggs,0.130,13.000,09:14,[1.95],"['Electric', 'Grass']","[{'num': '062', 'name': 'Poliwrath'}]","[{'num': '060', 'name': 'Poliwag'}]",554.0
63,64,64,Kadabra,http://www.serebii.net/pokemongo/pokemon/064.png,['Psychic'],1.30 m,56.5 kg,Abra Candy,100.0,Not in Eggs,0.027,2.700,11:25,[1.4],"['Bug', 'Ghost', 'Dark']","[{'num': '065', 'name': 'Alakazam'}]","[{'num': '063', 'name': 'Abra'}]",685.0
66,67,67,Machoke,http://www.serebii.net/pokemongo/pokemon/067.png,['Fighting'],1.50 m,70.5 kg,Machop Candy,100.0,Not in Eggs,0.034,3.400,10:32,[1.7],"['Flying', 'Psychic', 'Fairy']","[{'num': '068', 'name': 'Machamp'}]","[{'num': '066', 'name': 'Machop'}]",632.0
69,70,70,Weepinbell,http://www.serebii.net/pokemongo/pokemon/070.png,"['Grass', 'Poison']",0.99 m,6.4 kg,Bellsprout Candy,100.0,Not in Eggs,0.072,7.200,09:45,[1.59],"['Fire', 'Ice', 'Flying', 'Psychic']","[{'num': '071', 'name': 'Victreebel'}]","[{'num': '069', 'name': 'Bellsprout'}]",585.0
71,72,72,Tentacool,http://www.serebii.net/pokemongo/pokemon/072.png,"['Water', 'Poison']",0.89 m,45.5 kg,Tentacool Candy,50.0,5 km,0.810,81.000,03:20,[2.52],"['Electric', 'Ground', 'Psychic']","[{'num': '073', 'name': 'Tentacruel'}]",NaN,200.0
74,75,75,Graveler,http://www.serebii.net/pokemongo/pokemon/075.png,"['Rock', 'Ground']",0.99 m,105.0 kg,Geodude Candy,100.0,Not in Eggs,0.071,7.100,04:53,"[1.64, 1.72]","['Water', 'Grass', 'Ice', 'Fighting', 'Ground'...","[{'num': '076', 'name': 'Golem'}]","[{'num': '074', 'name': 'Geodude'}]",293.0
76,77,77,Ponyta,http://www.serebii.net/pokemongo/pokemon/077.png,['Fire'],0.99 m,30.0 kg,Ponyta Candy,50.0,5 km,0.510,51.000,02:50,"[1.48, 1.5]","['Water', 'Ground', 'Rock']","[{'num': '078', 'name': 'Rapidash'}]",NaN,170.0
78,79,79,Slowpoke,http://www.serebii.net/pokemongo/pokemon/079.png,"['Water', 'Psychic']",1.19 m,36.0 kg,Slowpoke Candy,50.0,5 km,1.050,105.000,07:12,[2.21],"['Electric', 'Grass', 'Bug', 'Ghost', 'Dark']","[{'num': '080', 'name': 'Slowbro'}]",NaN,432.0
80,81,81,Magnemite,http://www.serebii.net/pokemongo/pokemon/081.png,['Electric'],0.30 m,6.0 kg,Magnemite Candy,50.0,5 km,0.710,71.000,04:04,"[2.16, 2.17]","['Fire', 'Water', 'Ground']","[{'num': '082', 'name': 'Magneton'}]",NaN,244.0
83,84,84,Doduo,http://www.serebii.net/pokemongo/pokemon/084.png,"['Normal', 'Flying']",1.40 m,39.2 kg,Doduo Candy,50.0,5 km,0.520,52.000,05:10,"[2.19, 2.24]","['Electric', 'Rock']","[{'num': '085', 'name': 'Dodrio'}]",NaN,310.0
85,86,86,Seel,http://www.serebii.net/pokemongo/pokemon/086.png,['Water'],1.09 m,90.0 kg,Seel Candy,50.0,5 km,0.280,28.000,06:46,"[1.04, 1.96]","['Electric', 'Grass']","[{'num': '087', 'name': 'Dewgong'}]",NaN,406.0
87,88,88,Grimer,http://www.serebii.net/pokemongo/pokemon/088.png,['Poison'],0.89 m,30.0 kg,Grimer Candy,50.0,5 km,0.052,5.200,15:11,[2.44],"['Ground', 'Psychic']","[{'num': '089', 'name': 'Muk'}]",NaN,911.0
89,90,90,Shellder,http://www.serebii.net/pokemongo/pokemon/090.png,['Water'],0.30 m,4.0 kg,Shellder Candy,50.0,5 km,0.520,52.000,07:39,[2.65],"['Electric', 'Grass']","[{'num': '091', 'name': 'Cloyster'}]",NaN,459.0
92,93,93,Haunter,http://www.serebii.net/pokemongo/pokemon/093.png,"['Ghost', 'Poison']",1.60 m,0.1 kg,Gastly Candy,100.0,Not in Eggs,0.052,5.200,00:10,"[1.56, 1.8]","['Ground', 'Psychic', 'Ghost', 'Dark']","[{'num': '094', 'name': 'Gengar'}]","[{'num': '092', 'name': 'Gastly'}]",10.0
95,96,96,Drowzee,http://www.serebii.net/pokemongo/pokemon/096.png,['Psychic'],0.99 m,32.4 kg,Drowzee Candy,50.0,5 km,3.210,321.000,01:51,"[2.08, 2.09]","['Bug', 'Ghost', 'Dark']","[{'num': '097', 'name': 'Hypno'}]",NaN,111.0
97,98,98,Krabby,http://www.serebii.net/pokemongo/pokemon/098.png,['Water'],0.41 m,6.5 kg,Krabby Candy,50.0,5 km,2.120,212.000,03:33,"[2.36, 2.4]","['Electric', 'Grass']","[{'num': '099', 'name': 'Kingler'}]",NaN,213.0
99,100,100,Voltorb,http://www.serebii.net/pokemongo/pokemon/100.png,['Electric'],0.51 m,10.4 kg,Voltorb Candy,50.0,5 km,0.650,65.000,04:36,"[2.01, 2.02]",['Ground'],"[{'num': '101', 'name': 'Electrode'}]",NaN,276.0
101,102,102,Exeggcute,http://www.serebii.net/pokemongo/pokemon/102.png,"['Grass', 'Psychic']",0.41 m,2.5 kg,Exeggcute Candy,50.0,5 km,0.780,78.000,09:09,"[2.7, 3.18]","['Fire', 'Ice', 'Poison', 'Flying', 'Bug', 'Gh...","[{'num': '103', 'name': 'Exeggutor'}]",NaN,549.0
103,104,104,Cubone,http://www.serebii.net/pokemongo/pokemon/104.png,['Ground'],0.41 m,6.5 kg,Cubone Candy,50.0,5 km,0.610,61.000,01:51,[1.67],"['Water', 'Grass', 'Ice']","[{'num': '105', 'name': 'Marowak'}]",NaN,111.0
108,109,109,Koffing,http://www.serebii.net/pokemongo/pokemon/109.png,['Poison'],0.61 m,1.0 kg,Koffing Candy,50.0,5 km,0.200,20.000,08:16,[1.11],"['Ground', 'Psychic']","[{'num': '110', 'name': 'Weezing'}]",NaN,496.0
110,111,111,Rhyhorn,http://www.serebii.net/pokemongo/pokemon/111.png,"['Ground', 'Rock']",0.99 m,115.0 kg,Rhyhorn Candy,50.0,5 km,0.630,63.000,03:21,[1.91],"['Water', 'Grass', 'Ice', 'Fighting', 'Ground'...","[{'num': '112', 'name': 'Rhydon'}]",NaN,201.0
115,116,116,Horsea,http://www.serebii.net/pokemongo/pokemon/116.png,['Water'],0.41 m,8.0 kg,Horsea Candy,50.0,5 km,1.130,113.000,02:53,[2.23],"['Electric', 'Grass']","[{'num': '117', 'name': 'Seadra'}]",NaN,173.0
117,118,118,Goldeen,http://www.serebii.net/pokemongo/pokemon/118.png,['Water'],0.61 m,15.0 kg,Goldeen Candy,50.0,5 km,2.180,218.000,03:14,"[2.15, 2.2]","['Electric', 'Grass']","[{'num': '119', 'name': 'Seaking'}]",NaN,194.0
119,120,120,Staryu,http://www.serebii.net/pokemongo/pokemon/120.png,['Water'],0.79 m,34.5 kg,Staryu Candy,50.0,5 km,1.950,195.000,22:59,"[2.38, 2.41]","['Electric', 'Grass']","[{'num': '121', 'name': 'Starmie'}]",NaN,1379.0
128,129,129,Magikarp,http://www.serebii.net/pokemongo/pokemon/129.png,['Water'],0.89 m,10.0 kg,Magikarp Candy,400.0,2 km,4.780,478.000,14:26,"[10.1, 11.8]","['Electric', 'Grass']","[{'num': '130', 'name': 'Gyarados'}]",NaN,866.0
137,138,138,Omanyte,http://www.serebii.net/pokemongo/pokemon/138.png,"['Rock', 'Water']",0.41 m,7.5 kg,Omanyte Candy,50.0,10 km,0.140,14.000,10:23,[2.12],"['Electric', 'Grass', 'Fighting', 'Ground']","[{'num': '139', 'name': 'Omastar'}]",NaN,623.0
139,140,140,Kabuto,http://www.serebii.net/pokemongo/pokemon/140.png,"['Rock', 'Water']",0.51 m,11.5 kg,Kabuto Candy,50.0,10 km,0.100,10.000,00:05,"[1.97, 2.37]","['Electric', 'Grass', 'Fighting', 'Ground']","[{'num': '141', 'name': 'Kabutops'}]",NaN,5.0
147,148,148,Dragonair,http://www.serebii.net/pokemongo/pokemon/148.png,['Dragon'],3.99 m,16.5 kg,Dratini Candy,100.0,Not in Eggs,0.020,2.000,11:57,[2.05],"['Ice', 'Dragon', 'Fairy']","[{'num': '149', 'name': 'Dragonite'}]","[{'num': '147', 'name': 'Dratini'}]",717.0

In [6]:
df['spawn_time_seconds'] = pd.to_datetime(df['spawn_time'], format='%M:%S').dt.minute * 60 + pd.to_datetime(df['spawn_time'], format='%M:%S').dt.second
df[df['spawn_time_seconds'] < 300]



plt.figure(figsize=(8, 6))
plt.scatter(df['name'], df['spawn_time_seconds'])
plt.xlabel('Pokemon')
plt.ylabel('Spawn Time (seconds)')
plt.title('Spawn Time of Pokemons')
plt.xticks(rotation=90)
plt.show()

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution,spawn_time_seconds
6,7,7,Squirtle,http://www.serebii.net/pokemongo/pokemon/007.png,['Water'],0.51 m,9.0 kg,Squirtle Candy,25.0,2 km,0.5800,58.00,04:25,[2.1],"['Electric', 'Grass']","[{'num': '008', 'name': 'Wartortle'}, {'num': ...",NaN,265.0
8,9,9,Blastoise,http://www.serebii.net/pokemongo/pokemon/009.png,['Water'],1.60 m,85.5 kg,Squirtle Candy,NaN,Not in Eggs,0.0067,0.67,00:06,NaN,"['Electric', 'Grass']",NaN,"[{'num': '007', 'name': 'Squirtle'}, {'num': '...",6.0
10,11,11,Metapod,http://www.serebii.net/pokemongo/pokemon/011.png,['Bug'],0.71 m,9.9 kg,Caterpie Candy,50.0,Not in Eggs,0.1870,18.70,02:11,"[3.55, 3.79]","['Fire', 'Flying', 'Rock']","[{'num': '012', 'name': 'Butterfree'}]","[{'num': '010', 'name': 'Caterpie'}]",131.0
12,13,13,Weedle,http://www.serebii.net/pokemongo/pokemon/013.png,"['Bug', 'Poison']",0.30 m,3.2 kg,Weedle Candy,12.0,2 km,7.1200,712.00,02:21,"[1.01, 1.09]","['Fire', 'Flying', 'Psychic', 'Rock']","[{'num': '014', 'name': 'Kakuna'}, {'num': '01...",NaN,141.0
13,14,14,Kakuna,http://www.serebii.net/pokemongo/pokemon/014.png,"['Bug', 'Poison']",0.61 m,10.0 kg,Weedle Candy,50.0,Not in Eggs,0.4400,44.00,02:30,"[3.01, 3.41]","['Fire', 'Flying', 'Psychic', 'Rock']","[{'num': '015', 'name': 'Beedrill'}]","[{'num': '013', 'name': 'Weedle'}]",150.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127,128,128,Tauros,http://www.serebii.net/pokemongo/pokemon/128.png,['Normal'],1.40 m,88.4 kg,None,NaN,5 km,0.1200,12.00,00:37,NaN,['Fighting'],NaN,NaN,37.0
129,130,130,Gyarados,http://www.serebii.net/pokemongo/pokemon/130.png,"['Water', 'Flying']",6.50 m,235.0 kg,Magikarp Candy,NaN,Not in Eggs,0.0032,0.32,02:15,NaN,"['Electric', 'Rock']",NaN,"[{'num': '129', 'name': 'Magikarp'}]",135.0
134,135,135,Jolteon,http://www.serebii.net/pokemongo/pokemon/135.png,['Electric'],0.79 m,24.5 kg,None,NaN,Not in Eggs,0.0120,1.20,02:30,NaN,['Ground'],NaN,"[{'num': '133', 'name': 'Eevee'}]",150.0
136,137,137,Porygon,http://www.serebii.net/pokemongo/pokemon/137.png,['Normal'],0.79 m,36.5 kg,None,NaN,5 km,0.0120,1.20,02:49,NaN,['Fighting'],NaN,NaN,169.0
139,140,140,Kabuto,http://www.serebii.net/pokemongo/pokemon/140.png,"['Rock', 'Water']",0.51 m,11.5 kg,Kabuto Candy,50.0,10 km,0.1000,10.00,00:05,"[1.97, 2.37]","['Electric', 'Grass', 'Fighting', 'Ground']","[{'num': '141', 'name': 'Kabutops'}]",NaN,5.0

In [ ]:
df[df['type'].str.count(',') > 1]
df

plt.figure(figsize=(8, 6))
type_counts = more_than_2_types['type'].str.count(',').add(1)
plt.bar(more_than_2_types['name'], type_counts)
plt.xlabel('Pokemon')
plt.ylabel('Number of type')
plt.title('Pokemons with More than Two Types')
plt.xticks(rotation=90)
plt.show()

In [ ]:
Question 7 -
Using the data from Question 4, write code to analyze the data and answer the following questions Note -
1. Draw plots to demonstrate the analysis for the following questions for better visualizations
2. Write code comments wherever required for code understanding

Insights to be drawn -
● Get all the Earth meteorites that fell before the year 2000
● Get all the earth meteorites co-ordinates who fell before the year 1970
● Assuming that the mass of the earth meteorites was in kg, get all those whose mass was more
than 10000kg

In [21]:
import pandas as pd
import matplotlib.pyplot as plt

# Read the meteorite data from the CSV file
df = pd.read_csv('meteorite_data.csv')

# Convert the 'year' column to datetime type
df['year'] = pd.to_datetime(df['year'], errors='coerce')

# Get all the Earth meteorites that fell before the year 2000
earth_meteorites_before_2000 = df[(df['reclat'].notnull()) & (df['year'].dt.year < 2000)]

earth_meteorites_before_2000.to_csv('earth_meteorites_before_2000.csv', index=False)

# Get all the Earth meteorites coordinates that fell before the year 1970
earth_meteorites_coordinates_before_1970 = df[(df['reclat'].notnull()) & (df['year'].dt.year < 1970)]

earth_meteorites_coordinates_before_1970[['reclat', 'reclong']].to_csv('earth_meteorites_coordinates_before_1970.csv', index=False)

# Get all the Earth meteorites with mass greater than 10000kg
earth_meteorites_mass_more_than_10000kg = df[(df['reclat'].notnull()) & (df['mass'] > 10000)]

earth_meteorites_mass_more_than_10000kg.to_csv('earth_meteorites_mass_more_than_10000kg.csv', index=False)

In [ ]:
#Plotting the analysis results for better visualization

#Scatter plot for Earth meteorites before 2000
plt.figure(figsize=(8, 6))
plt.scatter(earth_meteorites_before_2000['reclat'], earth_meteorites_before_2000['reclong'], s=10)
plt.xlabel('Latitude')
plt.ylabel('Longitude')
plt.title('Earth Meteorites before 2000')
plt.show()

#Scatter plot for Earth meteorite coordinates before 1970
plt.figure(figsize=(8, 6))
plt.scatter(earth_meteorites_coordinates_before_1970['reclat'], earth_meteorites_coordinates_before_1970['reclong'], s=10)
plt.xlabel('Latitude')
plt.ylabel('Longitude')
plt.title('Earth Meteorite Coordinates before 1970')
plt.show()

#Histogram for Earth meteorites with mass greater than 10000kg
plt.figure(figsize=(8, 6))
plt.hist(earth_meteorites_mass_more_than_10000kg['mass'], bins=20)
plt.xlabel('mass')
plt.ylabel('Count')
plt.title('Earth Meteorites with Mass greater than 10000kg')
plt.show()

In [ ]:
Question 8 -
Using the data from Question 5, write code the analyze the data and answer the following questions Note -
1. Draw plots to demonstrate the analysis for the following questions and better visualizations
2. Write code comments wherever required for code understanding

Insights to be drawn -
● Get all the overall ratings for each season and using plots compare the ratings for all the
seasons, like season 1 ratings, season 2, and so on.
● Get all the episode names, whose average rating is more than 8 for every season
● Get all the episode names that aired before May 2019
● Get the episode name from each season with the highest and lowest rating
● Get the summary for the most popular ( ratings ) episode in every season

In [8]:
import pandas as pd
import requests
import json

# API URL
url = 'http://api.tvmaze.com/singlesearch/shows?q=westworld&embed=episodes'

# Make an HTTP GET request to the API and fetch the JSON data
response = requests.get(url)
data = response.json()

# Extract the episodes data from the JSON response
episodes = data['_embedded']['episodes']

# Convert the episodes data to a DataFrame
df = pd.DataFrame(episodes)

# Save the DataFrame to a CSV file
df.to_csv('westworld_episodes.csv', index=False)
df.head()

,id,url,name,season,number,type,airdate,airtime,airstamp,runtime,rating,image,summary,_links
0,869671,https://www.tvmaze.com/episodes/869671/westwor...,The Original,1,1,regular,2016-10-02,21:00,2016-10-03T01:00:00+00:00,68,{'average': 8},{'medium': 'https://static.tvmaze.com/uploads/...,<p>A woman named Dolores is a free spirit in t...,{'self': {'href': 'https://api.tvmaze.com/epis...
1,911201,https://www.tvmaze.com/episodes/911201/westwor...,Chestnut,1,2,regular,2016-10-09,21:00,2016-10-10T01:00:00+00:00,60,{'average': 7.7},{'medium': 'https://static.tvmaze.com/uploads/...,<p>Bernard suspects that someone is sabotaging...,{'self': {'href': 'https://api.tvmaze.com/epis...
2,911204,https://www.tvmaze.com/episodes/911204/westwor...,The Stray,1,3,regular,2016-10-16,21:00,2016-10-17T01:00:00+00:00,60,{'average': 7.6},{'medium': 'https://static.tvmaze.com/uploads/...,<p>Bernard continues to investigate Dolores' s...,{'self': {'href': 'https://api.tvmaze.com/epis...
3,911205,https://www.tvmaze.com/episodes/911205/westwor...,Dissonance Theory,1,4,regular,2016-10-23,21:00,2016-10-24T01:00:00+00:00,60,{'average': 7.9},{'medium': 'https://static.tvmaze.com/uploads/...,<p>While Dolores joins William and Logan on th...,{'self': {'href': 'https://api.tvmaze.com/epis...
4,927174,https://www.tvmaze.com/episodes/927174/westwor...,Contrapasso,1,5,regular,2016-10-30,21:00,2016-10-31T01:00:00+00:00,60,{'average': 8},{'medium': 'https://static.tvmaze.com/uploads/...,<p>Dolores takes the first step on her path of...,{'self': {'href': 'https://api.tvmaze.com/epis...

In [ ]:
df[df['airdate'] < '2019-05']
df

In [9]:
df.head()

,id,url,name,season,number,type,airdate,airtime,airstamp,runtime,rating,image,summary,_links
0,869671,https://www.tvmaze.com/episodes/869671/westwor...,The Original,1,1,regular,2016-10-02,21:00,2016-10-03T01:00:00+00:00,68,{'average': 8},{'medium': 'https://static.tvmaze.com/uploads/...,<p>A woman named Dolores is a free spirit in t...,{'self': {'href': 'https://api.tvmaze.com/epis...
1,911201,https://www.tvmaze.com/episodes/911201/westwor...,Chestnut,1,2,regular,2016-10-09,21:00,2016-10-10T01:00:00+00:00,60,{'average': 7.7},{'medium': 'https://static.tvmaze.com/uploads/...,<p>Bernard suspects that someone is sabotaging...,{'self': {'href': 'https://api.tvmaze.com/epis...
2,911204,https://www.tvmaze.com/episodes/911204/westwor...,The Stray,1,3,regular,2016-10-16,21:00,2016-10-17T01:00:00+00:00,60,{'average': 7.6},{'medium': 'https://static.tvmaze.com/uploads/...,<p>Bernard continues to investigate Dolores' s...,{'self': {'href': 'https://api.tvmaze.com/epis...
3,911205,https://www.tvmaze.com/episodes/911205/westwor...,Dissonance Theory,1,4,regular,2016-10-23,21:00,2016-10-24T01:00:00+00:00,60,{'average': 7.9},{'medium': 'https://static.tvmaze.com/uploads/...,<p>While Dolores joins William and Logan on th...,{'self': {'href': 'https://api.tvmaze.com/epis...
4,927174,https://www.tvmaze.com/episodes/927174/westwor...,Contrapasso,1,5,regular,2016-10-30,21:00,2016-10-31T01:00:00+00:00,60,{'average': 8},{'medium': 'https://static.tvmaze.com/uploads/...,<p>Dolores takes the first step on her path of...,{'self': {'href': 'https://api.tvmaze.com/epis...

In [ ]:
high_rated_episodes = df.groupby(['season', 'episode'])['rating'].mean().reset_index()
high_rated_episodes = high_rated_episodes[high_rated_episodes['rating'] > 8]

In [ ]:
df.loc[highest_rated_episodes, ['season', 'episode', 'rating']]
df

In [ ]:
df.loc[lowest_rated_episodes, ['season', 'episode', 'rating']]
df

In [ ]:
df.loc[most_popular_episodes, ['season', 'episode', 'summary']]
df

In [ ]:
#Plotting the ratings for each season
plt.figure(figsize=(8, 6))
plt.bar(season_ratings['season'], season_ratings['rating'])
plt.xlabel('Season')
plt.ylabel('Average Rating')
plt.title('Average Ratings for Each Season')
plt.show()

Question 9 -
Write a program to read the data from the following link, perform data analysis and answer the following
questions
Note -
1. Write code comments wherever required for code understanding
Link - https://data.wa.gov/api/views/f6w7-q2d2/rows.csv?accessType=DOWNLOAD
Insights to be drawn -
● Get all the cars and their types that do not qualify for clean alternative fuel vehicle
● Get all TESLA cars with the model year, and model type made in Bothell City.
● Get all the cars that have an electric range of more than 100, and were made after
2015
● Draw plots to show the distribution between city and electric vehicle type

In [15]:
import pandas as pd

# Read the data from the CSV file
url = "https://data.wa.gov/api/views/f6w7-q2d2/rows.csv?accessType=DOWNLOAD"
df = pd.read_csv(url)
df

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
0,5YJXCAE26J,Yakima,Yakima,WA,98908.0,2018,TESLA,MODEL X,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,238,0,14.0,141151601,POINT (-120.56916 46.58514),PACIFICORP,5.307700e+10
1,JHMZC5F37M,Kitsap,Poulsbo,WA,98370.0,2021,HONDA,CLARITY,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,47,0,23.0,171566447,POINT (-122.64681 47.73689),PUGET SOUND ENERGY INC,5.303509e+10
2,5YJ3E1EB0K,King,Seattle,WA,98199.0,2019,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,220,0,36.0,9426525,POINT (-122.40092 47.65908),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303301e+10
3,1N4AZ0CP5D,King,Seattle,WA,98119.0,2013,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,75,0,36.0,211807760,POINT (-122.3684 47.64586),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303301e+10
4,5YJSA1E21H,Thurston,Lacey,WA,98516.0,2017,TESLA,MODEL S,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,210,0,22.0,185810306,POINT (-122.75379 47.06316),PUGET SOUND ENERGY INC,5.306701e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130438,7SAYGDEE6P,Pierce,Gig Harbor,WA,98335.0,2023,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,26.0,231134102,POINT (-122.58354539999999 47.32344880000005),BONNEVILLE POWER ADMINISTRATION||CITY OF TACOM...,5.305307e+10
130439,1N4BZ1CV7N,Pierce,Tacoma,WA,98408.0,2022,NISSAN,LEAF,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,29.0,185810943,POINT (-122.43810499999995 47.203220000000044),BONNEVILLE POWER ADMINISTRATION||CITY OF TACOM...,5.305306e+10
130440,5YJYGDEE8M,King,Seattle,WA,98109.0,2021,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,36.0,176542418,POINT (-122.35022 47.63824),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303301e+10
130441,5YJXCBE22L,Island,Camano Island,WA,98282.0,2020,TESLA,MODEL X,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,293,0,10.0,102834938,POINT (-122.40049 48.23986),BONNEVILLE POWER ADMINISTRATION||PUD 1 OF SNOH...,5.302997e+10
130442,5YJ3E1EA5M,Pierce,Puyallup,WA,98375.0,2021,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,2.0,180473639,POINT (-122.30116 47.1165),BONNEVILLE POWER ADMINISTRATION||CITY OF TACOM...,5.305307e+10

In [16]:
print(df.columns)

Index(['VIN (1-10)', 'County', 'City', 'State', 'Postal Code', 'Model Year',
       'Make', 'Model', 'Electric Vehicle Type',
       'Clean Alternative Fuel Vehicle (CAFV) Eligibility', 'Electric Range',
       'Base MSRP', 'Legislative District', 'DOL Vehicle ID',
       'Vehicle Location', 'Electric Utility', '2020 Census Tract'],
      dtype='object')

In [ ]:
non_clean_cars = df[df['Clean_Alternative_Fuel_Vehicle_(CAFV)_Eligibility'] == 'No']
non_clean_cars_info = non_clean_cars[['Make', 'Type']]

In [ ]:
df[(df['Make'] == 'TESLA') & (df['City'] == 'BOTHELL')]

In [ ]:
df[(df['Electric Range (mi)'] > 100) & (df['Model Year'] > 2015)]

In [ ]:
Question 10 -
Write a program to count the number of verbs, nouns, pronouns, and adjectives in a given particular phrase or
paragraph, and return their respective count as a dictionary.
Note -
1. Write code comments wherever required for code
2. You have to write at least 2 additional test cases in which your program will run successfully and provide
an explanation for the same.

Example Output -

In [24]:
pip install nltk

Collecting nltk
  Downloading nltk-3.8.1-py3-none-any.whl (1.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 58.7 MB/s eta 0:00:00
Requirement already satisfied: joblib in /opt/conda/lib/python3.10/site-packages (from nltk) (1.2.0)
Collecting regex>=2021.8.3
  Downloading regex-2023.5.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (769 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 769.7/769.7 kB 60.5 MB/s eta 0:00:00
Requirement already satisfied: click in /opt/conda/lib/python3.10/site-packages (from nltk) (8.1.3)
Requirement already satisfied: tqdm in /opt/conda/lib/python3.10/site-packages (from nltk) (4.64.1)
Installing collected packages: regex, nltk
Successfully installed nltk-3.8.1 regex-2023.5.5
Note: you may need to restart the kernel to use updated packages.

In [25]:
import nltk

nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /home/jovyan/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/jovyan/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package stopwords to /home/jovyan/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [26]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

def count_pos_tags(text):
    # Tokenize the text into words
    tokens = word_tokenize(text)

    # Remove stopwords
    stop_words = set(stopwords.words('english'))
    filtered_tokens = [word for word in tokens if word.lower() not in stop_words]

    # Tag the tokens with their respective part-of-speech
    tagged_tokens = nltk.pos_tag(filtered_tokens)

    # Initialize counts
    counts = {'nouns': 0, 'verbs': 0, 'pronouns': 0, 'adjectives': 0}

    # Count the number of each part-of-speech
    for word, tag in tagged_tokens:
        if tag.startswith('N'):
            counts['nouns'] += 1
        elif tag.startswith('V'):
            counts['verbs'] += 1
        elif tag.startswith('P'):
            counts['pronouns'] += 1
        elif tag.startswith('J'):
            counts['adjectives'] += 1

    return counts

# Example usage
text = "The quick brown fox jumps over the lazy dog."
counts = count_pos_tags(text)
print(counts)

{'nouns': 4, 'verbs': 0, 'pronouns': 0, 'adjectives': 2}